name: ci

on: [push]

jobs:
  tests:
    name: Tests with Foundry
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.5
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - run: pnpm install

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Huff
        uses: huff-language/huff-toolchain@v2
        with:
          version: nightly

      - name: Run Tests
        run: forge test -vvv
